noislabs/nois-contracts

contracts/nois-sink/src/contract.rs
contracts/nois-sink/src/error.rs
contracts/nois-sink/src/msg.rs
contracts/nois-sink/src/state.rs

Sink native token

---

contracts/nois-gateway/src/contract.rs
contracts/nois-gateway/src/error.rs
contracts/nois-gateway/src/msg.rs
contracts/nois-gateway/src/state.rs
packages/multitest/tests/drand-gateway.rs
packages/multitest/tests/multitest.rs
tests/README.md
tests/package-lock.json
tests/package.json
tests/src/contracts.ts
tests/src/tests.spec.ts

This will remove immutability of the drand addr setting on  nois-gateway. the  manager will  be able to edit that
Closes #184
Closes #188

Gateway: add SetConfig to update manager, drand address and pricing

---

contracts/nois-payment/src/contract.rs

Let payment support zero amounts

---

tests/package-lock.json
tests/package.json
tests/src/tests.spec.ts

this gives us better access to events

Upgrade ts-relayer and CosmJS in tests

---

contracts/nois-gateway/src/contract.rs
contracts/nois-gateway/src/error.rs
contracts/nois-proxy/src/contract.rs
packages/nois-protocol/examples/schema.rs
packages/nois-protocol/src/ibc_msg.rs
packages/nois-protocol/src/lib.rs

Convert RequestBeaconPacket into an InPacket enum

---

tests/package-lock.json
tests/package.json
tests/src/ics20.spec.ts
tests/src/utils.ts

Add dedicated ICS-20 testing

---

tests/src/ics20.spec.ts

Fix for an issue created in https://github.com/noislabs/nois-contracts/pull/210

Fix height value for timeout

---

contracts/nois-payment/src/contract.rs

Change encode_msg_fund_community_pool arg to &Addr

---

contracts/nois-icecube/src/contract.rs
contracts/nois-icecube/src/msg.rs

This improves the codebase but contains no functional changes

Add unit tests for anonymous icecube claiming and sending

---

contracts/nois-proxy/src/contract.rs
contracts/nois-proxy/src/msg.rs

I think this is a nice addition. Let's use that part

Combine withdraw and withdraw all

---

CHANGELOG.md
Cargo.lock
contracts/nois-proxy/Cargo.toml
contracts/nois-proxy/examples/schema.rs
contracts/nois-proxy/src/contract.rs
contracts/nois-proxy/src/msg.rs

Add sudo messages to proxy

---

contracts/nois-proxy/src/contract.rs
contracts/nois-proxy/src/msg.rs

Issue introduced in #231 and found via #232

Fix spelling for SudoMsg::Withdraw

---

contracts/nois-airdrop/src/contract.rs
contracts/nois-airdrop/src/error.rs
contracts/nois-airdrop/src/msg.rs
contracts/nois-airdrop/src/state.rs

Closes https://github.com/noislabs/nois-contracts/issues/244

Randdrop review

---

CHANGELOG.md
contracts/nois-proxy/src/contract.rs
contracts/nois-proxy/src/error.rs
contracts/nois-proxy/src/msg.rs
contracts/nois-proxy/src/state.rs
packages/multitest/tests/drand-gateway.rs
packages/multitest/tests/multitest.rs
tests/src/contracts.ts
tests/src/setup.ts

Here I am not changing the airdrop contract because it has a much stricter check.

Check after values in proxy

---

CHANGELOG.md
contracts/nois-drand/src/bots.rs
contracts/nois-drand/src/contract.rs
contracts/nois-gateway/src/contract.rs
contracts/nois-gateway/src/request_router.rs
contracts/nois-proxy/src/publish_time.rs
contracts/nois-proxy/src/state.rs
packages/drand-common/src/lib.rs
packages/drand-common/src/rounds.rs
tests/src/bot.ts
tests/src/drand.spec.ts
tests/src/gateway.spec.ts
tests/src/payment.spec.ts
tests/src/proxy.spec.ts

Reverts noislabs/nois-contracts#251

Revert "change-drand-from-mod10-to-mod3"

---

Cargo.lock
contracts/nois-demo/Cargo.toml
contracts/nois-drand/Cargo.toml
contracts/nois-gateway/Cargo.toml
contracts/nois-icecube/Cargo.toml
contracts/nois-monitoring/Cargo.toml
contracts/nois-payment/Cargo.toml
contracts/nois-proxy/Cargo.toml
contracts/nois-proxy/src/contract.rs
contracts/nois-sink/Cargo.toml

Saves a bit of gas and makes code cleaner. Logic is the same.

Use Item::exists

---

CHANGELOG.md
Cargo.lock
contracts/nois-demo/Cargo.toml
contracts/nois-drand/Cargo.toml
contracts/nois-gateway/Cargo.toml
contracts/nois-gateway/src/contract.rs
contracts/nois-gateway/src/msg.rs
contracts/nois-gateway/src/state/drand_jobs/drand_jobs1.rs
contracts/nois-gateway/src/state/drand_jobs/mod.rs
contracts/nois-gateway/src/state/mod.rs
contracts/nois-icecube/Cargo.toml
contracts/nois-monitoring/Cargo.toml
contracts/nois-payment/Cargo.toml
contracts/nois-proxy-governance-owned/Cargo.toml
contracts/nois-proxy/Cargo.toml
contracts/nois-sink/Cargo.toml
packages/drand-common/Cargo.toml
packages/misc/Cargo.toml
packages/multitest/Cargo.toml
packages/nois-protocol/Cargo.toml

- Upgrade cosmwasm to 1.3.1
- Allow removing outdated key range
Closes #264

Add function to cleanup gateway

---

.circleci/config.yml
CHANGELOG.md
Cargo.lock
contracts/nois-demo/Cargo.toml
contracts/nois-drand/Cargo.toml
contracts/nois-gateway/Cargo.toml
contracts/nois-gateway/src/contract.rs
contracts/nois-gateway/src/request_router.rs
contracts/nois-icecube/Cargo.toml
contracts/nois-monitoring/Cargo.toml
contracts/nois-payment/Cargo.toml
contracts/nois-proxy-governance-owned/Cargo.toml
contracts/nois-proxy/Cargo.toml
contracts/nois-proxy/src/contract.rs
contracts/nois-sink/Cargo.toml
packages/drand-common/Cargo.toml
packages/misc/Cargo.toml
packages/multitest/Cargo.toml
packages/nois-protocol/Cargo.toml
packages/nois-protocol/examples/schema.rs
packages/nois-protocol/src/ibc_msg.rs
packages/nois-protocol/src/lib.rs

A PR to test this work: https://github.com/CosmWasm/cosmwasm/pull/1637
Once 1.4.0 is tagged, this can be finalized.

Use StdAck from cosmwasm-std

---

Cargo.lock
contracts/nois-payment/Cargo.toml
contracts/nois-proxy/Cargo.toml

No good reason to change other then boosting download stats of the new version

Bump anybuf to 0.3.0

---

Cargo.lock
packages/multitest/Cargo.toml

Hi @webmaster128,
I have upgraded MultiTest dependency to version 2.1.0.

Upgraded MultiTest to v2.1.0
